name: Run Daily Scripts

on:
  schedule:
    # 6:00 AM Nepal time = 00:15 UTC
    - cron: '15 0 * * *'
  workflow_dispatch:  # allows manual trigger

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    env:  # job-level env, applies to all steps
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install ./PYTHONCODES  

      - name: Run Motivation Script
        run: python -m PYTHONCODES.32.motivation.main

      - name: Run Rain Alert Script
        run: python -m PYTHONCODES.35.rainalert
